slogan: "游戏，游戏开发以及大数据"

theme: slate
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/qwertylevel3
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "blkstone"
    url: http://blkstone.github.io
    intro: "blkstone's blog"
    icon: "fa fa-github"
  - title: "freemind"
    url: hahack.com/codes/hexo-theme-freemind/
    intro: "freemind"
    icon: "fa fa-github"


widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname: qwertylevel3

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

